config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'tickets#index'
  resources :tickets, only: [:index, :show]
  
  namespace :api do
    namespace :v1 do
      match 'load', to: 'load#index', via: [:post]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/excavator.rb
class Excavator < ApplicationRecord
    belongs_to :ticket
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  has_many :excavators

  def get_geocode
    return well_known_text.remove('POLYGON').remove('(').remove(')').split(',').map(&:to_f).each_slice(2).to_a
  end
end

app/controllers/api/v1/api_controller.rb
class Api::V1::ApiController < ActionController::API
end

app/controllers/api/v1/load_controller.rb
class Api::V1::LoadController < Api::V1::ApiController
    def index
        begin
            ticket = Ticket.create(request_number: params[:RequestNumber],
                                sequence_number: params[:SequenceNumber],
                                request_type: params[:RequestType],
                                request_action: params[:RequestAction],
                                request_due_date_time: params[:DateTimes][:RequestTakenDateTime],
                                primary_service_area_code: params[:ServiceArea][:PrimaryServiceAreaCode][:SACode],
                                additional_service_area_codes: params[:ServiceArea][:AdditionalServiceAreaCodes][:SACode],
                                well_known_text: params[:ExcavationInfo][:DigsiteInfo][:WellKnownText])

            ticket.excavators.create(company_name: params[:Excavator][:CompanyName],
                                    address: address,
                                    crew_on_site: params[:Excavator][:CrewOnsite])
            render json: { message: 'Records created successfully!' }, status: :ok
        rescue Exception => e
            render json: { message: e.message }, status: :unprocessable_entity
        end
    end


    protected

    def address
        params[:Excavator][:Address] + "," + params[:Excavator][:City] + "," + params[:Excavator][:State] + "," + params[:Excavator][:Zip]
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/excavators_controller.rb
class ExcavatorsController < ApplicationController
    def index
    end

    def show
    end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
    def index
        @ticket_data = Ticket.includes(:excavators).all
    end

    def show
        @ticket = Ticket.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Geospat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tickets/index.html.erb
<h1>Ticket List</h1>
<table>
<style>
table {
  border-collapse: collapse;
  width: 100%;
}

th, td {
  text-align: left;
  padding: 8px;
}

table, th, td {
  border: 1px;
  border-style:solid;
  border-color: #F2F3F4 ;
}

tr:nth-child(even) {background-color: #f2f2f2;}
</style>
  <tr>
    <th>ID</th>
    <th>Request Number</th>
    <th>Sequence Number</th>
    <th>Request Type</th>
    <th>Request Action</th>
    <th>Response Due Date Time</th>
    <th>Primary Service Area Code</th>
    <th>Additional Service Area Codes</th>
    <th>Action</th>
  </tr>
  <% @ticket_data.each do |t| %>
    <tr>
    <td><%= t.id %></td>
    <td><%= t.request_number %></td>
    <td><%= t.sequence_number %></td>
    <td><%= t.request_type %></td>
    <td><%= t.request_action %></td>
    <td><%= t.request_due_date_time %></td>
    <td><%= t.primary_service_area_code %></td>
    <td><%= t.additional_service_area_codes.join(', ') %></td>
    <td><%= link_to "Show", ticket_path(t) %></td>
  </tr>
  <% end %>
</table>

app/views/tickets/show.html.erb
<h1>Ticket Detail</h1>
<h3>Excavators</h3>
<table>
<style>
table {
  border-collapse: collapse;
  width: 100%;
}

th, td {
  text-align: left;
  padding: 8px;
}
th{
  text-align: center;
  background-color: #f2f2f2;
}

table, th, td {
  border: 1px;
  border-style:solid;
  border-color: #CACFD2 ;
}

tr:nth-child(even) {background-color: #f2f2f2;}
</style>
  <tr>
    <th><b>Request Number</th><td><%= @ticket.request_number %></td>
  </tr>
  <tr>
    <th>Sequence Number</th><td><%= @ticket.sequence_number %></td>
  </tr>
  <tr>
    <th>Request Type</th><td><%= @ticket.request_type %></td>
  </tr>
  <tr>
    <th>Request Action</th><td><%= @ticket.request_action %></td>
  </tr>
  <tr>
    <th>Response Due Date Time</th><td><%= @ticket.request_due_date_time %></td>
  </tr>
  <tr>
    <th>Primary Service Area Code</th><td><%= @ticket.primary_service_area_code %></td>
  </tr>
   <tr>
    <th>Additional Service Area Codes</th><td><%= @ticket.additional_service_area_codes.join(', ') %></td>
  </tr>
  <tr>
    <th>Excavator - Company Name</th><td><%= @ticket.excavators.first.company_name %></td>
  </tr>
  <tr>
    <th>Excavator - Address</th><td><%= @ticket.excavators.first.address %></td>
  </tr>
  <tr>
    <th>Excavator - Crew on site</th><td><%= @ticket.excavators.first.crew_on_site %></td>
  </tr>
</table>

<h3>Dig site Map</h3>

<%= area_map [{geometry: {type: "Polygon", coordinates:  [@ticket.get_geocode]}, label: "Dig Site"}] %>